---

- hosts: ubuntus
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install apache2 package and php surpport for apache
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
