---

- hosts: ubuntus
  become: true
  tasks:

  - name: uninstall apache2 package and the rest
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: absent
      update_cache: yes
