---

- name: linux update
  hosts: ubuntus,workstations,centos
  become: True
  tasks:

    - name: upgrade all ubuntus daily
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"
      register: upgrade_result_ubuntus

    - name: upgrade centos daily
      yum:
        update_cache: yes
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"
      register: upgrade_result_centos


    - name: check the ubuntus upgrade's results
      debug:
        msg: "ubuntus result: {{ upgrade_result_ubuntus }}"
      when: upgrade_result_ubuntus is defined

    - name: check the centos upgrade's results
      debug:
        msg: "centOS result: {{ upgrade_result_centos }}"
      when: upgrade_result_centos is defined



    - name: daily upgrade
      cron:
        name: "daily upgrade"
        minute: "0"
        hour: "5"
        job: "ansible-playbook /home/jiadai/.ansible/ansibletest/test/upgrade.yml"


- name: windows update
  hosts: winservers
  become: True
  become_method: runas
  become_user: SYSTEM
  tasks:

    - name: install windows updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes
      register: update_result_win

    - name: check the update's results
      debug:
        msg: "result: {{ update_result_win }}"
      when: update_result_win is defined

    - name: daily update plan
      win_scheduled_task:
        name: "Daily winservers update"
        description: "automatic daily update"
        actions:
          - path: "powershell.exe"
            arguments: "-ExecutionPolicy Bypass -File C:\\ansibletest\\win_update.ps1"
        trigger:
          - type: daily
            start_boundary: '2024-06-11T05:00:00'
        username: "SYSTEM"
        state: present
  
