---

- name: linux update
  hosts: ubuntus
  become: True
  tasks:

    - name: upgrade all ubuntus daily
      apt:
        update_cache: yes
        upgrade: dist
      register: upgrade_result
       
        #registermodule is to define the whole result of the task as a variable and can be call later.


    - name: check the upgrade's results
      debug:
        msg: "result: {{ upgrade_result }}"
      when: upgrade_result is defined


    - name: daily upgrade
      cron:
        name: "daily upgrade"
        minute: "0"
        hour: "5"
        job: "ansible-playbook /home/jiadai/.ansible/ansibletest/test/upgrade.yml"


- name: windows update
  hosts: winservers
  become: True
  become_method: runas
  become_user: SYSTEM
  tasks:

    - name: install windows updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes
      register: update_result_win

    - name: check the update's results
      debug:
        msg: "result: {{ update_result_win }}"
      when: update_result_win is defined

    - name: daily update plan
      win_scheduled_task:
        name: "Daily winservers update"
        description: "automatic daily update"
        actions:
          - path: "powershell.exe"
            arguments: "-ExecutionPolicy Bypass -File C:\\ansibletest\\win_update.ps1"
        trigger:
          - type: daily
            start_boundary: '2024-06-11T05:00:00'
        username: "SYSTEM"
        state: present
  
